### ISSUE TITLE
Can not make a 'live' transaction with authorize.net's test servers.

### ISSUE THREAD

**Issue by jcavalieri** [Shopify/active_merchant#1642] opened 2015-04-07 16:20 UTC
I'm integrating testing of authorizing and capturing using the authorize.net gateway and found what I believe to be a bug in the authorization.net gateway.

Essentially in order to test authorization and capture with authorize.net's test servers the transactions to those test servers need to be 'live' transactions.

I believe the bug exists here:
https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb#L367

Specifically, whether or not to use test servers and whether or not mark the transaction as a test transaction is using the same "test?" method.

```
url = (test? ? test_url : live_url)
```
and

```
Response.new(
            success_from(response),
            message_from(response, avs_result, cvv_result),
            response,
            authorization: authorization_from(response),
            test: test?,
```
Therefore truly testing authorization and capture on authorize.net's test severs is impossible because the authorization call returns a bogus transaction id which is then rejected when the capture call is made with that id.

I'd be glad to help with a PR but would like some guidance on how best to handle this.

-John

**Comment by bacrossland** [comment] 2015-04-07 16:22
:+1:

**Comment by girasquid** [comment] 2015-04-07 16:51
> the authorization call returns a bogus transaction id which is then rejected when the capture call is made with that id.

Can you share a test case that reproduces this? [This test](https://github.com/Shopify/active_merchant/blob/ab46446aebb18eaa44ed1d92e11b5bedf94b03d0/test/remote/gateways/remote_authorize_net_test.rb#L68-L75) does a capture after an authorization against Authorize.Net [with the gateway in test mode](https://github.com/Shopify/active_merchant/blob/ab46446aebb18eaa44ed1d92e11b5bedf94b03d0/test/test_helper.rb#L18), and seems to work. What does the bogus authorization look like? What error do you get?

**Comment by jcavalieri** [comment] 2015-04-07 17:37
Let me fork and look into it more.

**Comment by girasquid** [comment] 2015-04-07 17:38
Ok - going to close this for now. Re-open it when you've got a test case for me. :)

**Closed by girasquid** 2015-04-07 17:38 UTC

**Comment by jcavalieri** [comment] 2015-04-07 18:23
The remote test does indeed work.

I figured what is going on. It is the existence of option[:test] key when initializing the gateway. When it is set to false the gateway uses neither the test servers nor test requests. But setting option[:test] to true uses both the test servers and test requests.

What works is setting the base mode to test and not even having a option[:test] key when initializing the gateway. This doesn't seem intuitive to me but I don't know if this counts as a an issue anymore.

**Comment by girasquid** [comment] 2015-04-07 19:03
I think I'm missing something - what you're describing sounds like intended behavior:

1) When you set `test` to `true`, transactions are processed against the test servers.
2) When you set `test` to `false`, transactions are processed against the live servers.
3) When you set `test` to `true` on the base gateway, transactions are processed against the test servers.

Have I misunderstood somewhere?

**Comment by jcavalieri** [comment] 2015-04-07 19:14
At least for authorize.net there is a test request feature, where whether you are on their live servers or their test servers you can send a 'test' request and it sends you a bogus response. This is more intended for integrating with their live servers to verify the app is connected and they are receiving requests.

In order to test auth and capture the request can not be a test request.

base test = true, gateway option test = true, then test requests are sent to test servers
base test = true, gateway option test = false, then non-test requests are sent to live servers
base test = false, gateway option test = true, then test requests are sent to test servers
base test = false, gateway option test = false, then non-test requests are sent to live servers 

This is the case that is different, and what I needed, and why the remote tests work:
base test = true, gateway option test key doesn't exists, then non-test requests are set to test servers

IMO, the test option has been overloaded and used to determine both test servers and test requests. And a using test requests should be a totally separate option.

**Comment by girasquid** [comment] 2015-04-07 19:30
I understand now - thanks for the clarification.

It looks like the changes from https://github.com/Shopify/active_merchant/pull/924 didn't make it across when the Authorize.Net integration was updated a few months ago - I don't have time to get to adding this for you, but you could open a PR to re-add support for the option (along with a test to make sure we don't remove it accidentally next time).

**Comment by jcavalieri** [comment] 2015-04-07 19:36
Oh yeah, that is exactly what I was thinking it should be. I'll craft a PR this week. Thanks for the help.

**Comment by jcavalieri** [comment] 2015-04-14 20:49
Sorry I didn't get to this last week. Looking at it now.

**Comment by jcavalieri** [comment] 2015-04-15 18:57
Hi @girasquid,

I'm about to create a PR. What version should this be? 1.49.0 or 1.48.1?

Thanks,
John

**Comment by ntalbott** [comment] 2015-04-15 18:58
@jcavalieri don't update anything version or changelog related please - just the code would be great.

**Comment by girasquid** [comment] 2015-04-15 18:58
Don't touch the version, we can handle that

**Comment by jcavalieri** [comment] 2015-04-15 18:59
Ok, thanks.

**Comment by jcavalieri** [comment] 2015-04-15 19:01
Here's the pr:
https://github.com/Shopify/active_merchant/pull/1648

**Comment by jcavalieri** [comment] 2015-04-22 19:02
Just following up. I see the PR is still out there. Are there any issues I need to address?

https://github.com/Shopify/active_merchant/pull/1648

Thanks,
John

**Comment by girasquid** [comment] 2015-04-22 19:04
No, just haven't had a chance to review it yet. It's on my list. :)

**Comment by jcavalieri** [comment] 2015-04-22 19:14
Ok, no problem.
